<?php
return array(
	'application_env' => 'production',
	'editor' => 'none',
	'list_limit' => '20',
	'helpurl' => 'http://www.hubzero.org',
	'debug' => '1',
	'debug_lang' => '0',
	'feed_limit' => '10',
	'feed_email' => '',
	'secret' => 'gnkhyMFuC2',
	'gzip' => '0',
	'error_reporting' => 'default',
	'api_server' => '1',
	'xmlrpc_server' => '',
	'log_path' => '/var/www/public/app/logs',
	'tmp_path' => '/var/www/public/app/tmp',
	'live_site' => '',
	'force_ssl' => '0',
	'offset' => 'America/New_York',
	'sitename' => 'example',
	'robots' => '',
	'captcha' => '0',
	'access' => '1',
);
